stages:
  - build
  - docker

build-prod:
  stage: build
  only:
    - master
  image: node:14.17.6-alpine3.14
  script:
    - yarn --cache-folder .yarn
    - yarn build # build project
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - .yarn
      - node_modules
  artifacts:
    expire_in: 1 week
    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    paths:
      - build

docker-prod:
  stage: docker
  image: docker:stable
  services:
    - name: docker:dind
      alias: dind
  variables:
    # Tell docker CLI how to talk to Docker daemon; see
    # https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#use-docker-in-docker-executor
    DOCKER_HOST: tcp://dind:2375/
    # Use the overlayfs driver for improved performance:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - master
